import "./globals.css";
import { Inter } from "next/font/google";
import ProviderWrapper from "@/utils/AuthProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const authSession = await getServerSession(authOptions);

  return (
    <html lang="en">
      {/* <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200;400&display=swap"
          rel="stylesheet"
        />
      </head> */}
      <ProviderWrapper session={authSession}>
        <body
        // className={inter.className}
        >
          {children}
          {/* {children} */}
        </body>
      </ProviderWrapper>
    </html>
  );
}
